name: Workflow de Build/Teste para Projeto .NET

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora

jobs:
  build:
    name: Build do Projeto
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v2

      - name: Configurar o .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore github4women/github4women.csproj

      - name: Construir a aplicação
        run: dotnet build github4women/github4women.csproj --configuration Release

      - name: Executar testes
        run: dotnet test github4women/github4women.csproj --configuration Release

  publish:
    name: Empacotar e Verificar Qualidade
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v2

      - name: Configurar o .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Formatar o código
        run: |
          dotnet tool install --global dotnet-format
          dotnet format github4women/github4women.csproj --check

      - name: Limpar arquivos temporários
        run: rm -rf github4women/bin github4women/obj

      - name: Empacotar aplicação para deploy
        run: dotnet publish github4women/github4women.csproj --configuration Release --output ./publish
